name: Release
on: push

jobs:
  bump_version:
    name: Bump version and create a new tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag/create release point
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 0.1.0
          RELEASE_BRANCHES: ".*"
          DEFAULT_BUMP: patch
      - name: Get the latest version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - name: Write the latest version to file
        run: |
          echo "${{ steps.get-latest-tag.outputs.tag }}"
          echo "${{ steps.get-latest-tag.outputs.tag }}" > version.txt
  release:
    name: Build and Release
    needs: bump_version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rpilot
            asset_name: rpilot-linux-amd64
          - os: macos-latest
            artifact_name: rpilot
            asset_name: rpilot-macos-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read the latest version
        run: |
          value=`cat version.txt`
          echo "$value"
          echo "$value" > $TAG_VERSION
      - name: Build project
        run: cargo build --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ env.TAG_VERSION }}
